export const dashboardStyles = {
    sectionCard: {
        mb: 3,
        borderRadius: 3,
        overflow: 'hidden',
        border: '1px solid rgba(0,0,0,0.08)',
    },
    sectionHeader: {
        px: 3,
        py: 2,
        backgroundColor: 'grey.50',
        borderBottom: '1px solid rgba(0,0,0,0.08)',
    },
    sectionTitle: {
        fontWeight: 600,
        color: 'text.primary',
        display: 'flex',
        alignItems: 'center',
        gap: 1,
    },
    sectionBody: {
        p: 3,
    },
    twoColumnGrid: {
        display: 'grid',
        gridTemplateColumns: {xs: '1fr', md: '1fr 1fr'},
        gap: 3,
    },
    chartContainer: {
        width: '100%',
        height: 320,
    },
    heatmapGrid: {
        display: 'grid',
        gridTemplateColumns: 'auto repeat(24, 1fr)',
        gap: '2px',
        overflowX: 'auto',
    },
    heatmapCell: {
        aspectRatio: '1',
        borderRadius: 0.5,
        minWidth: 18,
        minHeight: 18,
        transition: 'transform 0.1s',
        cursor: 'pointer',
        '&:hover': {
            transform: 'scale(1.3)',
            zIndex: 1,
        },
    },
    heatmapLabel: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-end',
        pr: 1,
        fontSize: '0.75rem',
        color: 'text.secondary',
        fontWeight: 500,
        minWidth: 40,
    },
    rankingTable: {
        '& .MuiTableCell-head': {
            backgroundColor: '#f5f5f5',
            fontWeight: 600,
            fontSize: '0.875rem',
        },
        '& .MuiTableCell-body': {
            fontSize: '0.875rem',
        },
    },
    filterContainer: {
        mb: 3,
        display: 'flex',
        flexWrap: 'wrap',
        gap: 1,
        alignItems: 'center',
    },
    medalIcon: {
        width: 24,
        height: 24,
        borderRadius: '50%',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 'bold',
        fontSize: '0.75rem',
        color: 'white',
    },
    statChip: {
        display: 'flex',
        alignItems: 'center',
        gap: 1,
        p: 2,
        borderRadius: 2,
        backgroundColor: 'grey.50',
        border: '1px solid',
        borderColor: 'grey.200',
    },
};
